[project]
name = "ComfyUI-JakeUpgrade"
description = "ComfyUI workflow customization by Jake."
version = "1.0.9"
license = "LICENSE"
dependencies = ["opencv-python", "piexif", "torch", "numpy", "numexpr", "simpleeval"]

[project.urls]
Repository = "https://github.com/jakechai/ComfyUI-JakeUpgrade"

[tool.comfy]
PublisherId = "jakechai"
DisplayName = "ComfyUI-JakeUpgrade"
Icon = ""
